name: CI/CD Pipeline

# Trigger: Run this whenever 'main' branch receives a push
on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: TEST THE CODE
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python tests.py

# JOB 2: DEPLOY TO AWS (Only runs if 'test' passes)
  deploy:
    needs: test  # <--- The Magic Link! Wait for test to succeed.
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to AWS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd warehouse-app
          git pull origin main
          docker compose down
          docker compose up -d --build
		echo "waiting for 10 secs.."
		sleep 15          
	  # Optional: Run DB init again just in case schemas changed
		docker compose exec -T web python -c "from app import db, app; app.app_context().push(); db.create_all()"
